<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Stripe Payment</title>
  <script src="https://js.stripe.com/v3/"></script>
  <style>
    body { font-family: 'Roboto', sans-serif; padding: 20px; background: #f6f9fc; display: flex; justify-content: center; align-items: center; height: 100vh; }
    .container { max-width: 400px; background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); }
    .row { margin-bottom: 15px; }
    label { display: block; font-weight: 500; margin-bottom: 5px; }
    input { width: 100%; padding: 10px; border: 1px solid #ccc; border-radius: 4px; }
    #card-element { padding: 10px; border: 1px solid #ccc; border-radius: 4px; }
    button { width: 100%; padding: 10px; background: #6772e5; color: #fff; border: none; border-radius: 4px; cursor: pointer; font-size: 16px; }
    button:hover { background: #5469d4; }
    .error { color: red; margin-top: 15px; }
    .success { color: green; margin-top: 15px; }
  </style>
</head>
<body>
  <div class="container">
    <h1>Complete Your Payment</h1>
    <form id="payment-form">
      <div class="row">
        <label for="name">Name</label>
        <input id="name" type="text" placeholder="Jane Doe" required autocomplete="name">
      </div>
      <div class="row">
        <label for="email">Email</label>
        <input id="email" type="email" placeholder="janedoe@gmail.com" required autocomplete="email">
      </div>
      <div class="row">
        <label for="card-element">Card Information</label>
        <div id="card-element"><!-- Stripe Elements will be inserted here --></div>
      </div>
      <button id="submit">Pay Now</button>
      <div id="error-message" class="error"></div>
    </form>
    <div id="success-message" class="success" style="display:none;">Payment successful!</div>
  </div>

  <script>
    const stripe = Stripe('your_stripe_public_key');
    const elements = stripe.elements();
    const cardElement = elements.create('card');
    cardElement.mount('#card-element');

    const form = document.getElementById('payment-form');
    form.addEventListener('submit', async (event) => {
      event.preventDefault();
      const { token, error } = await stripe.createToken(cardElement);
      if (error) {
        document.getElementById('error-message').textContent = error.message;
      } else {
        document.getElementById('error-message').textContent = '';
        const response = await fetch('https://your-server-endpoint.com/process_payment', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ token: token.id, email: document.getElementById('email').value, name: document.getElementById('name').value })
        });
        const result = await response.json();
        if (result.success) {
          document.getElementById('success-message').style.display = 'block';
        } else {
          document.getElementById('error-message').textContent = 'Payment failed.';
        }
      }
    });
  </script>
</body>
</html>
